name: Push a Docker Image 
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python bikeshare_model/train_pipeline.py
    - uses: actions/upload-artifact@v2
      with:
        name: my-trained-pipeline
        path: bikeshare_model/trained_models/*.pkl
        retention-days: 1
  test:
    needs: train
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-pipeline
        path: bikeshare_model/trained_models
    - name: Install dependencies
      run: pip install -r requirements/test_requirements.txt
    - name: Test with pytest
      run: pytest
  lint:
    needs: [train, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install pylint
      - name: pylint the setup file
        run:  pylint setup.py
  black:
    needs: [train, test, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install black
      - name: black the setup file
        run:  black .
  build:
    needs: [train, test, lint, black]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: actions/download-artifact@v2
      with:
        name: my-trained-pipeline
        path: biekeshare_model/trained_models
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v2
      with:
        name: my-build-package
        path: dist/*.whl
        retention-days: 1
      
  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: my-build-package
        path: bikeshare_model_api
    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run : docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      run: docker build . -f Dockerfile -t $DOCKER_USER/bikeshare_fast_api:latest
    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      run: docker push $DOCKER_USER/bikeshare_fast_api
    - name: Logout to Docker hub
      run: docker logout
